### ISSUE TITLE
fixvalues in 702 not available?

### ISSUE THREAD

**Issue by oblomov-dev** [abapedia/steampunk-2305-api-intersect-702#4]
This issue came up:
https://github.com/abap2UI5/abap2UI5/issues/1310

So when fixvalues is not available in 702 we need to delete this lines:
https://github.com/abapedia/steampunk-2305-api-intersect-702/blob/d84c51bce673c9ae61209bef6460e820d5b395af/src/cl_abap_elemdescr.clas.abap#L18

I can create a PR as a next step, when this is the right way.

**Comment by larshp** [comment]
feel free to PR it

**Comment by oblomov-dev** [comment]
👍
https://github.com/abapedia/steampunk-2305-api-intersect-702/pull/5
